import { Series } from '../../../Construction/Components/ConstructionVisual/Types';
import { SwcrPackage } from '../../models/SwcrPackage';
import { createOpenSeries } from '../createSeries';
import { getLastWeeks } from '../graphUtils';

describe('create 2', () => {
    it('should return somethign', () => {
        const categories = getLastWeeks(3);
        const series = createOpenSeries(testData, categories);
        const expected: Series[] = [{ data: [3, 2, 1], label: 'Open' }];
        expect(series[0].data).toStrictEqual(expected[0].data);
    });
});

const testData: SwcrPackage[] = [
    {
        siteCode: 'JCA',
        projectIdentifier: 'L.O532C.002',
        projectDescription: 'Johan Castberg Facilities Project',
        swcrNo: '2465',
        title: 'Eng System 43 - Logic for dynamic range on 43HCV0021 (CQ-NOR-J-0054)',
        description:
            'Logic for dynamic range is missing for process condition where: \n1.At BXL, 43HCV0021 maximum range output (Ymax) is 100%. \n2.In between BXL and BXH, 43HCV0021 maximum range output (Ymax) is 50%. \n3.At BXH, 43HCV0021 maximum range output (Ymax) is 20%. \n4.At BXHH,43HCV0021 maximum range output (Ymax) is 10%\n\nABB to update SAS SW as per attached SCD.\nNote 2 Update\n',
        modification: '',
        priority: '',
        system: '43',
        controlSystem: 'PCS',
        contract: 'AS EPma',
        action: '',
        supplier: '',
        node: 'U03',
        status: 'Not initiated',
        referenceTypes: '',
        types: 'SIM,SW',
        createdAtDate: '2022/03/13',
        updatedAtDate: '2021/11/10',
        dueAtDate: '',
        closedAtDate: '2022/03/24',
        nextToSign: 'SWCR Originator',
        estimatedManhours: '',
        cntAttachments: '2',
        cpkgNo: '4301-M01',
        cpkgPhase: 'CIT',
        cpkgStartPlannedAtDate: '2021/08/26',
        cpkgStartForecastAtDate: '2023/06/25',
        cpkgFinishPlannedAtDate: '',
        cpkgFinishForecastAtDate: '',
        url: 'https://procosys.equinor.com/JOHAN_CASTBERG/SWAP/SWCR/#id=116518492',
        latestSignRanking: '',
        nextSignRanking: '1',
        swcrId: '116518492',
        rowKey: '2465',
        nextsToSign: ['SWCR Originator'],
    },
    {
        siteCode: 'JCA',
        projectIdentifier: 'L.O532C.002',
        projectDescription: 'Johan Castberg Facilities Project',
        swcrNo: '2835',
        title: 'Eng: Modbus Link Failure - Pig Detection (Node U04)',
        description:
            'This SWCR is part of standardizing solution for Modbus communication failure across different SAS Modbus packages (ref SWCR 2151).\nImplementation to be done as per IGG Modbus implementation in SWCR 2151.\n\n\n- New HMI display (Modbus Link Failure) is needed for this link.\n- Affected CBM application/ SCM: U04_13\n',
        modification:
            '14.12.2021/AKSO/KRJO: attaching SW report and SCD for MB blocks for modbus link failures.',
        priority: 'MEDIUM',
        system: '13',
        controlSystem: 'PCS',
        contract: 'SBM FC',
        action: '',
        supplier: '',
        node: 'U04',
        status: 'Not initiated',
        referenceTypes: '',
        types: 'SW',
        createdAtDate: '2022/03/08',
        updatedAtDate: '2021/12/14',
        dueAtDate: '',
        closedAtDate: '2022/03/14',
        nextToSign: 'SWCR Originator (Person: ABEH@EQUINOR.COM (Behery,Amr))',
        estimatedManhours: '',
        cntAttachments: '2',
        cpkgNo: '1301-T01',
        cpkgPhase: 'CIS',
        cpkgStartPlannedAtDate: '2021/09/12',
        cpkgStartForecastAtDate: '2023/10/08',
        cpkgFinishPlannedAtDate: '',
        cpkgFinishForecastAtDate: '',
        url: 'https://procosys.equinor.com/JOHAN_CASTBERG/SWAP/SWCR/#id=116889176',
        latestSignRanking: '',
        nextSignRanking: '1',
        swcrId: '116889176',
        rowKey: '2835',
        nextsToSign: ['SWCR Originator (Person: ABEH@EQUINOR.COM (Behery,Amr))'],
    },
    {
        siteCode: 'JCA',
        projectIdentifier: 'L.O532C.002',
        projectDescription: 'Johan Castberg Facilities Project',
        swcrNo: '2835',
        title: 'Eng: Modbus Link Failure - Pig Detection (Node U04)',
        description:
            'This SWCR is part of standardizing solution for Modbus communication failure across different SAS Modbus packages (ref SWCR 2151).\nImplementation to be done as per IGG Modbus implementation in SWCR 2151.\n\n\n- New HMI display (Modbus Link Failure) is needed for this link.\n- Affected CBM application/ SCM: U04_13\n',
        modification:
            '14.12.2021/AKSO/KRJO: attaching SW report and SCD for MB blocks for modbus link failures.',
        priority: 'MEDIUM',
        system: '13',
        controlSystem: 'PCS',
        contract: 'SBM FC',
        action: '',
        supplier: '',
        node: 'U04',
        status: 'Not initiated',
        referenceTypes: '',
        types: 'SW',
        createdAtDate: '2022/03/08',
        updatedAtDate: '2021/12/14',
        dueAtDate: '',
        closedAtDate: '',
        nextToSign: 'SWCR Originator (Person: ABEH@EQUINOR.COM (Behery,Amr))',
        estimatedManhours: '',
        cntAttachments: '2',
        cpkgNo: '1301-T01',
        cpkgPhase: 'CIS',
        cpkgStartPlannedAtDate: '2021/09/12',
        cpkgStartForecastAtDate: '2023/10/08',
        cpkgFinishPlannedAtDate: '',
        cpkgFinishForecastAtDate: '',
        url: 'https://procosys.equinor.com/JOHAN_CASTBERG/SWAP/SWCR/#id=116889176',
        latestSignRanking: '',
        nextSignRanking: '1',
        swcrId: '116889176',
        rowKey: '2835',
        nextsToSign: ['SWCR Originator (Person: ABEH@EQUINOR.COM (Behery,Amr))'],
    },
];
