import { DateTime } from 'luxon';
import { Series } from '../../../Construction/Components/ConstructionVisual/Types';
import { SwcrPackage } from '../../models/SwcrPackage';
import { getLastWeeks } from '../graphUtils';
import { createCreatedClosedSeries } from '../createSeries';

describe('create series', () => {
    const categories = getLastWeeks();
    const output: Series[] = [
        { label: 'Created', data: [0, 1, 1] },
        { label: 'Closed', data: [1, 0, 1] },
    ];
    it('should create', () => {
        const series = createCreatedClosedSeries(mockdata, categories);
        console.log(series);
    });
});

const mockdata: SwcrPackage[] = [
    {
        siteCode: 'JCA',
        projectIdentifier: 'L.O532C.002',
        projectDescription: 'Johan Castberg Facilities Project',
        swcrNo: '2465',
        title: 'Eng System 43 - Logic for dynamic range on 43HCV0021 (CQ-NOR-J-0054)',
        description:
            'Logic for dynamic range is missing for process condition where: \n1.At BXL, 43HCV0021 maximum range output (Ymax) is 100%. \n2.In between BXL and BXH, 43HCV0021 maximum range output (Ymax) is 50%. \n3.At BXH, 43HCV0021 maximum range output (Ymax) is 20%. \n4.At BXHH,43HCV0021 maximum range output (Ymax) is 10%\n\nABB to update SAS SW as per attached SCD.\nNote 2 Update\n',
        modification: '',
        priority: '',
        system: '43',
        controlSystem: 'PCS',
        contract: 'AS EPma',
        action: '',
        supplier: '',
        node: 'U03',
        status: 'Not initiated',
        referenceTypes: '',
        types: 'SIM,SW',
        createdAtDate: '2021/06/15',
        updatedAtDate: '2021/11/10',
        dueAtDate: '',
        closedAtDate: '',
        nextToSign: 'SWCR Originator',
        estimatedManhours: '',
        cntAttachments: '2',
        cpkgNo: '4301-M01',
        cpkgPhase: 'CIT',
        cpkgStartPlannedAtDate: '2021/08/26',
        cpkgStartForecastAtDate: '2023/06/25',
        cpkgFinishPlannedAtDate: '',
        cpkgFinishForecastAtDate: '',
        url: 'https://procosys.equinor.com/JOHAN_CASTBERG/SWAP/SWCR/#id=116518492',
        latestSignRanking: '',
        nextSignRanking: '1',
        swcrId: '116518492',
        rowKey: '2465',
        nextsToSign: ['SWCR Originator'],
    },
    {
        siteCode: 'JCA',
        projectIdentifier: 'L.O532C.002',
        projectDescription: 'Johan Castberg Facilities Project',
        swcrNo: '2835',
        title: 'Eng: Modbus Link Failure - Pig Detection (Node U04)',
        description:
            'This SWCR is part of standardizing solution for Modbus communication failure across different SAS Modbus packages (ref SWCR 2151).\nImplementation to be done as per IGG Modbus implementation in SWCR 2151.\n\n\n- New HMI display (Modbus Link Failure) is needed for this link.\n- Affected CBM application/ SCM: U04_13\n',
        modification:
            '14.12.2021/AKSO/KRJO: attaching SW report and SCD for MB blocks for modbus link failures.',
        priority: 'MEDIUM',
        system: '13',
        controlSystem: 'PCS',
        contract: 'SBM FC',
        action: '',
        supplier: '',
        node: 'U04',
        status: 'Not initiated',
        referenceTypes: '',
        types: 'SW',
        createdAtDate: '2021/10/21',
        updatedAtDate: '2021/12/14',
        dueAtDate: '',
        closedAtDate: '',
        nextToSign: 'SWCR Originator (Person: ABEH@EQUINOR.COM (Behery,Amr))',
        estimatedManhours: '',
        cntAttachments: '2',
        cpkgNo: '1301-T01',
        cpkgPhase: 'CIS',
        cpkgStartPlannedAtDate: '2021/09/12',
        cpkgStartForecastAtDate: '2023/10/08',
        cpkgFinishPlannedAtDate: '',
        cpkgFinishForecastAtDate: '',
        url: 'https://procosys.equinor.com/JOHAN_CASTBERG/SWAP/SWCR/#id=116889176',
        latestSignRanking: '',
        nextSignRanking: '1',
        swcrId: '116889176',
        rowKey: '2835',
        nextsToSign: ['SWCR Originator (Person: ABEH@EQUINOR.COM (Behery,Amr))'],
    },
    {
        siteCode: 'JCA',
        projectIdentifier: 'L.O532C.002',
        projectDescription: 'Johan Castberg Facilities Project',
        swcrNo: '2836',
        title: 'Eng: Modbus Link Failure - Analyser (Node U05)',
        description:
            'This SWCR is part of standardizing solution for Modbus communication failure across different SAS Modbus packages (ref SWCR 2151).\nImplementation to be done as per IGG Modbus implementation in SWCR 2151.\n\n\n- No Modbus failure HMI display is needed for this link.\n- Affected CBM application/ SCM: U05_EI198_Modbus\n',
        modification:
            '14.12.2021/AKSO/KRJO: attaching SW report and SCD for MB blocks for modbus link failures.',
        priority: 'MEDIUM',
        system: '87',
        controlSystem: 'PCS',
        contract: 'SBM FC',
        action: '',
        supplier: '',
        node: 'U05',
        status: 'Not initiated',
        referenceTypes: '',
        types: 'SW',
        createdAtDate: '2021/10/21',
        updatedAtDate: '2021/12/14',
        dueAtDate: '',
        closedAtDate: '',
        nextToSign: 'SWCR Originator (Person: ABEH@EQUINOR.COM (Behery,Amr))',
        estimatedManhours: '',
        cntAttachments: '2',
        cpkgNo: '',
        cpkgPhase: '',
        cpkgStartPlannedAtDate: '',
        cpkgStartForecastAtDate: '',
        cpkgFinishPlannedAtDate: '',
        cpkgFinishForecastAtDate: '',
        url: 'https://procosys.equinor.com/JOHAN_CASTBERG/SWAP/SWCR/#id=116889177',
        latestSignRanking: '',
        nextSignRanking: '1',
        swcrId: '116889177',
        rowKey: '2836',
        nextsToSign: ['SWCR Originator (Person: ABEH@EQUINOR.COM (Behery,Amr))'],
    },
    {
        siteCode: 'JCA',
        projectIdentifier: 'L.O532C.002',
        projectDescription: 'Johan Castberg Facilities Project',
        swcrNo: '2851',
        title: 'Eng: Modbus Link Failure - SAM (Node L04)',
        description:
            'This SWCR is part of standardizing solution for Modbus communication failure across different SAS Modbus packages (ref SWCR 2151).\nImplementation to be done as per IGG Modbus implementation in SWCR 2151.\n\n\n- No Modbus failure HMI display is needed for this link.\n- Affected CBM application/ SCM: L04_ER254_Modbus\n',
        modification:
            '14.12.2021/AKSO/KRJO: attaching SW report and SCD for MB blocks for modbus link failures.\n',
        priority: 'MEDIUM',
        system: '84',
        controlSystem: 'PCS',
        contract: 'SCM FC',
        action: '',
        supplier: '',
        node: 'L04',
        status: 'Not initiated',
        referenceTypes: '',
        types: 'SW',
        createdAtDate: '2021/10/21',
        updatedAtDate: '2021/12/14',
        dueAtDate: '',
        closedAtDate: '',
        nextToSign: 'SWCR Originator',
        estimatedManhours: '',
        cntAttachments: '2',
        cpkgNo: '',
        cpkgPhase: '',
        cpkgStartPlannedAtDate: '',
        cpkgStartForecastAtDate: '',
        cpkgFinishPlannedAtDate: '',
        cpkgFinishForecastAtDate: '',
        url: 'https://procosys.equinor.com/JOHAN_CASTBERG/SWAP/SWCR/#id=116889117',
        latestSignRanking: '',
        nextSignRanking: '1',
        swcrId: '116889117',
        rowKey: '2851',
        nextsToSign: ['SWCR Originator'],
    },
    {
        siteCode: 'JCA',
        projectIdentifier: 'L.O532C.002',
        projectDescription: 'Johan Castberg Facilities Project',
        swcrNo: '2877',
        title: 'ECOM SW - HMI updates found during ECOM',
        description:
            'GTG-1 and GTG-2 layout updated according to the instalment in the field.\n\n26.11.2021 : for GTG1 / GTG2 ZSL HMI changes as per attached document needs to be done in Master System',
        modification: 'Main system HMI needs to be update according to ECOM HMI. ',
        priority: '',
        system: '70',
        controlSystem: 'SAS',
        contract: 'AS EPma',
        action: '',
        supplier: '',
        node: '',
        status: 'Not initiated',
        referenceTypes: '',
        types: 'ECOM',
        createdAtDate: '2021/10/27',
        updatedAtDate: '2021/11/26',
        dueAtDate: '2022/02/01',
        closedAtDate: '',
        nextToSign: 'SWCR Originator',
        estimatedManhours: '',
        cntAttachments: '2',
        cpkgNo: '8010-M01',
        cpkgPhase: 'ECOM',
        cpkgStartPlannedAtDate: '2021/07/26',
        cpkgStartForecastAtDate: '2023/12/03',
        cpkgFinishPlannedAtDate: '',
        cpkgFinishForecastAtDate: '',
        url: 'https://procosys.equinor.com/JOHAN_CASTBERG/SWAP/SWCR/#id=116901727',
        latestSignRanking: '',
        nextSignRanking: '1',
        swcrId: '116901727',
        rowKey: '2877',
        nextsToSign: ['SWCR Originator'],
    },
    {
        siteCode: 'JCA',
        projectIdentifier: 'L.O532C.002',
        projectDescription: 'Johan Castberg Facilities Project',
        swcrNo: '2901',
        title: 'ENG. HW Changes Hull 84JC601 (DCR-KI-4200)',
        description: 'C\n',
        modification: 'STIDloop shall be updated accordingly.\n\n',
        priority: '',
        system: '87',
        controlSystem: 'PCS',
        contract: 'SCM FC',
        action: '',
        supplier: '',
        node: 'L04',
        status: 'Not initiated',
        referenceTypes: '',
        types: 'HW',
        createdAtDate: '2021/11/02',
        updatedAtDate: '2021/12/01',
        dueAtDate: '',
        closedAtDate: '',
        nextToSign: 'SWCR Originator (Person: ESNA@EQUINOR.COM (Næss,Espen))',
        estimatedManhours: '',
        cntAttachments: '0',
        cpkgNo: '8740-H06',
        cpkgPhase: 'COS',
        cpkgStartPlannedAtDate: '2021/04/16',
        cpkgStartForecastAtDate: '2023/03/19',
        cpkgFinishPlannedAtDate: '',
        cpkgFinishForecastAtDate: '',
        url: 'https://procosys.equinor.com/JOHAN_CASTBERG/SWAP/SWCR/#id=116916255',
        latestSignRanking: '',
        nextSignRanking: '1',
        swcrId: '116916255',
        rowKey: '2901',
        nextsToSign: ['SWCR Originator (Person: ESNA@EQUINOR.COM (Næss,Espen))'],
    },
    {
        siteCode: 'JCA',
        projectIdentifier: 'L.O532C.002',
        projectDescription: 'Johan Castberg Facilities Project',
        swcrNo: '2903',
        title: 'ER271 SRU - MAIN - FS rev 10 #XXX, DCR-KR-4050. Modification of controling 29PV0444 & 29PV0445',
        description:
            'Two new PVs (29PV0444 and 29PV0445) are needed for running NF CIP and NF HP pump in serie. \nSimulator testing has shown that current design as per TH FS Rev.10 #74 is not stable enough for use.\n\nFollowing points from simulator testsheet cover the topic: NC28B, NC32, NC35a\n\n**HOLD** Waiting for feedback from Techouse to the solution proposed by simulator.',
        modification: '',
        priority: 'HIGH',
        system: '29',
        controlSystem: 'PCS',
        contract: 'AS EPma',
        action: '',
        supplier: '',
        node: 'C08',
        status: 'Not initiated',
        referenceTypes: '',
        types: 'SW',
        createdAtDate: '2021/11/02',
        updatedAtDate: '2021/11/03',
        dueAtDate: '',
        closedAtDate: '',
        nextToSign: 'SWCR Originator (Person: PETR.SIMUNEK@AKERSOLUTIONS.COM (Simunek,Petr))',
        estimatedManhours: '',
        cntAttachments: '0',
        cpkgNo: '2901-M05',
        cpkgPhase: 'CIT',
        cpkgStartPlannedAtDate: '2021/10/01',
        cpkgStartForecastAtDate: '2024/03/25',
        cpkgFinishPlannedAtDate: '',
        cpkgFinishForecastAtDate: '',
        url: 'https://procosys.equinor.com/JOHAN_CASTBERG/SWAP/SWCR/#id=116916365',
        latestSignRanking: '',
        nextSignRanking: '1',
        swcrId: '116916365',
        rowKey: '2903',
        nextsToSign: ['SWCR Originator (Person: PETR.SIMUNEK@AKERSOLUTIONS.COM (Simunek,Petr))'],
    },
    {
        siteCode: 'JCA',
        projectIdentifier: 'L.O532C.002',
        projectDescription: 'Johan Castberg Facilities Project',
        swcrNo: '2957',
        title: 'ER271 SRU - MAIN - Changes to UF and NF/MDA',
        description:
            '1. Valves from SRU to WI shall closed if 29PT0211 has AHH or ALL. The ALL action is not implemented yet and is added in this SWCR.\n2. \n\nTODO:\n-U19A2a1 update of min.speed for 29PA007. HOLD - Awaiting input from TH.\n-U30?? HOLD Awaiting input from PP/Sim.testing & TH.\n\n.... (wait with the initiating SWCR in case there are other issues). The change i n 1. is not critical for simulator testing',
        modification: '',
        priority: 'MEDIUM',
        system: '29',
        controlSystem: 'PCS',
        contract: 'AS EPma',
        action: '',
        supplier: '',
        node: 'C08',
        status: 'Not initiated',
        referenceTypes: '',
        types: 'SW',
        createdAtDate: '2021/11/16',
        updatedAtDate: '2021/12/01',
        dueAtDate: '',
        closedAtDate: '',
        nextToSign: 'SWCR Originator (Person: PETR.SIMUNEK@AKERSOLUTIONS.COM (Simunek,Petr))',
        estimatedManhours: '',
        cntAttachments: '2',
        cpkgNo: '2901-M01',
        cpkgPhase: 'CIT',
        cpkgStartPlannedAtDate: '2021/10/01',
        cpkgStartForecastAtDate: '2023/10/29',
        cpkgFinishPlannedAtDate: '',
        cpkgFinishForecastAtDate: '',
        url: 'https://procosys.equinor.com/JOHAN_CASTBERG/SWAP/SWCR/#id=116943049',
        latestSignRanking: '',
        nextSignRanking: '1',
        swcrId: '116943049',
        rowKey: '2957',
        nextsToSign: ['SWCR Originator (Person: PETR.SIMUNEK@AKERSOLUTIONS.COM (Simunek,Petr))'],
    },
    {
        siteCode: 'JCA',
        projectIdentifier: 'L.O532C.002',
        projectDescription: 'Johan Castberg Facilities Project',
        swcrNo: '2964',
        title: 'ENG: HULL HW 87JF002A (DCR-CC-4375)',
        description: 'f',
        modification: 'STID to be updated accordingly.',
        priority: '',
        system: '87',
        controlSystem: 'PCS',
        contract: 'SCM FC',
        action: '',
        supplier: '',
        node: 'U03',
        status: 'Not initiated',
        referenceTypes: '',
        types: 'HW',
        createdAtDate: '2021/11/18',
        updatedAtDate: '2021/11/18',
        dueAtDate: '2021/01/24',
        closedAtDate: '',
        nextToSign: 'SWCR Originator (Person: SYAP@EQUINOR.COM (Yap,Shang Seen))',
        estimatedManhours: '',
        cntAttachments: '0',
        cpkgNo: '8705-H03',
        cpkgPhase: 'COS',
        cpkgStartPlannedAtDate: '2020/10/07',
        cpkgStartForecastAtDate: '2021/10/31',
        cpkgFinishPlannedAtDate: '',
        cpkgFinishForecastAtDate: '',
        url: 'https://procosys.equinor.com/JOHAN_CASTBERG/SWAP/SWCR/#id=116949820',
        latestSignRanking: '',
        nextSignRanking: '1',
        swcrId: '116949820',
        rowKey: '2964',
        nextsToSign: ['SWCR Originator (Person: SYAP@EQUINOR.COM (Yap,Shang Seen))'],
    },
    {
        siteCode: 'JCA',
        projectIdentifier: 'L.O532C.002',
        projectDescription: 'Johan Castberg Facilities Project',
        swcrNo: '2970',
        title: 'Comm: FDA AS1400 - AS1500 HMI / Graphic & Logic Issues (System 70)',
        description:
            '1. HMI Maintenance \n1.1 AS1509A - Group Effect Safeguard for E9 is missing on FDA Maintenance Page\n1.2 AS1509A -  Group Effect Safeguard for E19 and E22 to be swapped\n1.3 AS1509A - Group Effect Blocking is not matching correct effect groups / shoould be moved 1 down starting on "Isoler non-Ex gr.3 mekventomr akt" until "CCTV" effect\n1.4 AS1530A -  Group Effect Safeguard for E20 and E22 to be swapped\n1.5 AS1530A - Group Effect Blocking is not matching correct effect groups\n1.6 NT-F03-E01-6032 - change tag description to "Isoler gruppe 1B & 2 equipment AFT"\n\n2. Layout Graphics Changes\n2.1 AS1400 - arrange L3 graphics HMI according to attached Layout Drawing AS1400\n2.2 AS1500 - arrange L3 graphics HMI according to attached Layout Drawing AS1500\n2.3 AV100 - arrange L3 graphics HMI according to attached Layout Drawing AV100\n2.4 70SOAS1102A-310-02 - relocate object on L3 HMI layout graphics from AS1102A to AS1502A\n\n3. Logic Change  \n3.1 AS1531A - Area reset is not linked to F03 Autronica Fire Central\n3.2 AS1509A - "Isoler non-Ex Gr.3 mekventomr akt NT-F03-E01-6030" E9 in C&E - mising Group effect Safeguard object in maintenance page\n',
        modification: '',
        priority: '',
        system: '70',
        controlSystem: 'F&G',
        contract: 'SCM FC',
        action: '',
        supplier: '',
        node: 'F03',
        status: 'Not initiated',
        referenceTypes: '',
        types: 'SW',
        createdAtDate: '2021/11/22',
        updatedAtDate: '2021/11/23',
        dueAtDate: '',
        closedAtDate: '',
        nextToSign: 'SWCR Originator (Person: JUAF@EQUINOR.COM (Feliciano,Juan Paolo Antonio))',
        estimatedManhours: '',
        cntAttachments: '0',
        cpkgNo: '7000-H08',
        cpkgPhase: 'COS',
        cpkgStartPlannedAtDate: '2021/11/06',
        cpkgStartForecastAtDate: '2023/03/19',
        cpkgFinishPlannedAtDate: '',
        cpkgFinishForecastAtDate: '',
        url: 'https://procosys.equinor.com/JOHAN_CASTBERG/SWAP/SWCR/#id=116957275',
        latestSignRanking: '',
        nextSignRanking: '1',
        swcrId: '116957275',
        rowKey: '2970',
        nextsToSign: ['SWCR Originator (Person: JUAF@EQUINOR.COM (Feliciano,Juan Paolo Antonio))'],
    },
    {
        siteCode: 'JCA',
        projectIdentifier: 'L.O532C.002',
        projectDescription: 'Johan Castberg Facilities Project',
        swcrNo: '2978',
        title: 'Comm: AL600 Group Effect Safeguard',
        description:
            '"Isoler gruppe 1A utstyr" group effect safeguard object is duplicated on the start fire pump and the object for the start fire pump is missing\n\nThe following FDA\'s are affected:\n- AL617A\n- AL619A\n- AL620A',
        modification: '',
        priority: '',
        system: '70',
        controlSystem: 'F&G',
        contract: 'SCM FC',
        action: '',
        supplier: '',
        node: 'F08',
        status: 'Not initiated',
        referenceTypes: '',
        types: 'SW',
        createdAtDate: '2021/11/23',
        updatedAtDate: '2021/11/23',
        dueAtDate: '',
        closedAtDate: '',
        nextToSign: 'SWCR Originator (Person: JUAF@EQUINOR.COM (Feliciano,Juan Paolo Antonio))',
        estimatedManhours: '',
        cntAttachments: '0',
        cpkgNo: '7002-L06',
        cpkgPhase: 'COS',
        cpkgStartPlannedAtDate: '2021/03/05',
        cpkgStartForecastAtDate: '2023/06/18',
        cpkgFinishPlannedAtDate: '',
        cpkgFinishForecastAtDate: '',
        url: 'https://procosys.equinor.com/JOHAN_CASTBERG/SWAP/SWCR/#id=116960197',
        latestSignRanking: '',
        nextSignRanking: '1',
        swcrId: '116960197',
        rowKey: '2978',
        nextsToSign: ['SWCR Originator (Person: JUAF@EQUINOR.COM (Feliciano,Juan Paolo Antonio))'],
    },
    {
        siteCode: 'JCA',
        projectIdentifier: 'L.O532C.002',
        projectDescription: 'Johan Castberg Facilities Project',
        swcrNo: '3040',
        title: 'Eng System 62: Additional Level Safety Transmitter on Diesel Overflow Tank (DCR-KP-4641)',
        description:
            'As per DCR:\n- New LST (62LST6149-AHH) to be connected to P02  node and it shall initiate shutdown of pumps 62PA602A/B.\n- Move below function blocks and associated signals (FSE) from P03 to P02 node\n62PA602A-Q006\n62PA602B-Q006\n62PA602A-Q002\n62PA602B-Q002\n62PST6133\nPSD4-62-2\n\nABB to update PSD logic and IO connections as per attached documentation.',
        modification: '',
        priority: '',
        system: '62',
        controlSystem: 'PSD',
        contract: 'AS EPma',
        action: '',
        supplier: '',
        node: 'P02',
        status: 'Not initiated',
        referenceTypes: '',
        types: 'SW',
        createdAtDate: '2021/12/08',
        updatedAtDate: '2021/12/08',
        dueAtDate: '',
        closedAtDate: '',
        nextToSign: 'SWCR Originator',
        estimatedManhours: '',
        cntAttachments: '0',
        cpkgNo: '6201-H02',
        cpkgPhase: 'COS',
        cpkgStartPlannedAtDate: '2021/10/15',
        cpkgStartForecastAtDate: '2021/11/28',
        cpkgFinishPlannedAtDate: '',
        cpkgFinishForecastAtDate: '',
        url: 'https://procosys.equinor.com/JOHAN_CASTBERG/SWAP/SWCR/#id=117002827',
        latestSignRanking: '',
        nextSignRanking: '1',
        swcrId: '117002827',
        rowKey: '3040',
        nextsToSign: ['SWCR Originator'],
    },
];
