export * from './DetailsTab';
export * from './McPackagesTab';
export * from './NcrTab';
export * from './PunchTab';
export * from './QueryTab';
export * from './SwcrTab';
export * from './UnsignedActionTab';
export * from './UnsignedTasksTab';
export * from './WorkOrdersTab';
