version: "3.8"

services:
  web:
    image: node:20.9-alpine
    container_name: radix-web_container
    stdin_open: true # because of https://github.com/facebook/create-react-app/issues/8688
    working_dir: /app
    command: [ "sh", "-c", "pnpm install && chown -R node:node node_modules && pnpm start" ]
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: node-modules
        target: /app/node_modules
    networks:
      - radix
    ports:
      - "3000:3000"

volumes:
  node-modules:
    name: radix-web_node-modules

networks:
  radix:
    name: radix
