apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
    name: lighthouse-client-test
spec:
    environments:
        - name: dev
          build:
              from: feat/radix
    components:
        - name: frontend
          src: '.'
          variables:
              AUTH_CONFIG: ''
              JC_CONFIG: 'bcd'
          ports:
              - name: http
                port: 3000
          publicPort: http
          environmentConfig:
              - environment: dev
                resources:
                    requests:
                        memory: '1024Mi'
                        cpu: '800m'
                    limits:
                        memory: '4096Mi'
                        cpu: '800m'
