apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: lighthouse-client
spec:
  dnsExternalAlias:
    - alias: jc.fusion.dev.equinor.com
      environment: dev
      component: frontend
      useCertificateAutomation: true

    - alias: jc.fusion.equinor.com
      environment: prod
      component: frontend
      useCertificateAutomation: true

  environments:
    - name: dev
      build:
        from: dev
    - name: dev2
      build:
        from: dev2
    - name: prod
      build:
        from: main

  components:
    - name: frontend
      src: "."
      variables:
        AUTH_CONFIG: ""
        JC_CONFIG: ""
        SERVICE_MESSAGE: ""
      ports:
        - name: http
          port: 8080
      publicPort: http
      environmentConfig:
        - environment: dev
          resources:
            requests:
              memory: "512Mi"
              cpu: "400m"
            limits:
              memory: "4096Mi"
              cpu: "800m"
        - environment: dev2
          resources:
            requests:
              memory: "512Mi"
              cpu: "400m"
            limits:
              memory: "4096Mi"
              cpu: "800m"
        - environment: prod
          resources:
            requests:
              memory: "1024Mi"
              cpu: "800m"
            limits:
              memory: "4096Mi"
              cpu: "800m"
