export type Loop = {
    callOffNo: string | null;
    checklistId: string;
    checklistUrlId: string;
    commissioningPackageNo: string | null;
    commissioningPackageUrlId: string | null;
    description: string | null;
    facility: string | null;
    formularGroup: string | null;
    formularType: string | null;
    function: string | null;
    functionalSystem: string | null;
    isVoided: boolean | null;
    location: string | null;
    loopContentStatus: string | null;
    loopId: string;
    loopUrlId: string | null;
    loopNo: string;
    needDate: Date | null;
    mechanicalCompletionPackageNo: string | null;
    mechanicalCompletionPackageUrlId: string | null;
    packageNo: string | null;
    priority1: string | null;
    priority2: string | null;
    priority3: string | null;
    project: string | null;
    register: string | null;
    remainingManHours: number | null;
    responsible: string | null;
    revision: string | null;
    rfC_Planned_Forecast_Date: Date | null;
    rfO_Planned_Forecast_Date: Date | null;
    isOverdue: number | null;
    signedDate: string | null;
    status: string | null;
    system: string | null;
    tagStatus: string | null;
    verifiedDate: Date | null;
    loopContentProgress: number | null;
    woPlannedCompletionDate: Date | null;
    woActualCompletionDate: Date | null;
};
