export type Loop = {
    // sourceIdentity: string;
    // facility: string;
    // project: string | null;
    // loopNo: string | null;
    // description: string | null;
    // functionalSystem: string | null;
    // commissioningPackageNo: string | null;
    // mechanicalCompletionPackageNo: string | null;
    // priority1: null;
    // c01PlannedDate: Date | null;
    // c01ForecastDate: Date | null;
    // c07PlannedDate: Date | null;
    // c07ForecastDate: Date | null;
    // status: string | null;
    // responsible: string | null;
    // signedDate: Date | null;
    // verifiedDate: Date | null;
    // firstMechanicalCompletionStatus: string | null;
    // lastPlannedCompletionDate: Date | null;
    // lastActualCompletionDate: Date | null;
    // sumRemainingManHours: string | null;
    callOffNo: string | null;
    checklistId: string | null;
    commissioningPackageNo: string | null;
    commissioningPackage_ID: string | null;
    facility: string | null;
    formularGroup: string | null;
    formularType: string | null;
    function: string | null;
    functionalSystem: string | null;
    isVoided: boolean | null;
    location: string | null;
    loopContentStatus: string | null;
    loopId: string | null;
    mcpkgId: string | null;
    mechanicalCompletionPackageNo: string | null;
    packageNo: string | null;
    priority1: string | null;
    priority2: string | null;
    priority3: string | null;
    project: string | null;
    register: string | null;
    responsible: string | null;
    revision: string | null;
    rfC_Planned_Forecast_Date: Date | null;
    rfO_Planned_Forecast_Date: Date | null;
    signedDate: string | null;
    status: string | null;
    system: string | null;
    tagNo: string | null;
    verifiedDate: Date | null;
    woPlannedCompletionDate: Date | null;
};
