export enum QueryKeys {
    Scopechange = 'scopechange',
    History = 'history',
    Change = 'change',
    CommPkg = 'commPkg',
    Document = 'document',
    Tag = 'tag',
    Systems = 'systems',
    Discipline = 'discipline',
    Area = 'area',
    Step = 'step',
    Contributor = 'contributor',
    Criteria = 'criteria',
    FunctionalRole = 'functionalrole',
    References = 'references',
}
