export interface WorkOrder {
    projectIdentifier: string;
    workOrderNumber: string;
    description: string;
    disciplineCode: string;
    discipline: string;
    responsibleCode: string;
    responsible: string;
    milestoneCode?: any;
    mileStone?: string | null;
    materialStatus?: string | null;
    plannedStartupDate: string;
    plannedFinishDate: string;
    w1ActualDate?: string | null;
    w2ActualDate: Date;
    w3ActualDate: Date;
    w4ActualDate: Date;
    w5ActualDate?: string | null;
    w6ActualDate: string | null;
    w7ActualDate?: string | null;
    w8ActualDate?: string | null;
    w9ActualDate?: string | null;
    w10ActualDate?: string | null;
    commpkgNumber?: string | null;
    workOrderId: string;
    materialComments?: string | null;
    constructionComments?: string | null;
    projectProgress: number;
    estimatedHours: number;
    remainingHours: number;
    expendedHours?: string | null;
    mccrStatus?: string | null;
    holdBy: string;
    holdByDescription: string;
    jobStatus: string;
    facility: string;
    actualStartupDate: Date;
    actualCompletionDate: Date;
}
