trigger:
  branches:
    include:
      - main
      - dev

resources:
  repositories:
    - repository: self
    - repository: templates
      type: github
      name: equinor/lighthouse-infra
      endpoint: 'equinor'
      ref: infra/move_web_dynatrace

# Global variables for the pipeline
variables:
  - template: /src/resources/web-client/web-client-variables.yml@templates
  - template: /src/variables/global-variables.yml@templates

  - name: 'repositoryName'
    value: lighthouse-client

stages:
  # build_stage stage. Docker build, tag and push
  - stage: build
    displayName: 'Docker - Build and Push'
    variables:
      envName: 'build'
      envLabel: 'non-prod'
      envRg: '${{ variables.envRgName }}'
      serviceConnection: '${{ variables.nonProdServiceConnection }}'
      envGroupName: '$(globalPrefix)-$(fullAppName)-${{ variables.envName }}'
      dockerfilePath: '/.docker/Dockerfile'

    jobs:
      # Docker Build
      - template: /src/resources/web-client/jobs/client-dockerbuild.yml@templates
        parameters:
          dependsOn: ''
          condition: and(always(), eq(variables['Build.Reason'], 'PullRequest'))
          deploymentName: 'docker_build'
          envGroup: '${{ variables.envGroupName }}'
          buildCommand: build
          dockerfilePath: '${{ variables.dockerfilePath }}'
          repository: '${{ variables.repositoryName }}'
          dockerRegistryServiceConnection: '${{ variables.dockerRegistryServiceConnectionName }}'

      # Docker Build and Push
      - template: /src/resources/web-client/jobs/client-dockerbuild.yml@templates
        parameters:
          dependsOn: ''
          condition: and(always(), ne(variables['Build.Reason'], 'PullRequest'))
          deploymentName: 'docker_build_push'
          envGroup: '${{ variables.envGroupName }}'
          envLabel: '${{ variables.envLabel }}'
          buildCommand: buildAndPush
          dockerfilePath: '${{ variables.dockerfilePath }}'
          repository: '${{ variables.repositoryName }}'
          dockerRegistryServiceConnection: '${{ variables.dockerRegistryServiceConnectionName }}'
          kvName: '${{ variables.kvSharedName }}'
          kvRgName: '${{ variables.kvSharedRgName }}'
          serviceConnection: '${{ variables.serviceConnection }}'

  # Deploy to dev environment
  - stage: dev
    displayName: 'Deploy to dev'
    dependsOn: 'build'
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/dev'))
    variables:
      envName: 'dev'
      envLabel: 'non-prod'
      configURI: '${{ variables.functionAppName }}'
      rgName: '${{ variables.envRgName }}'
      envGroupName: '$(globalPrefix)-$(fullAppName)-${{ variables.envName }}'
      serviceConnection: '${{ variables.nonProdServiceConnection }}'
      containerRegistry: '${{ variables.containerRegistryName }}'

    jobs:
      - template: /src/resources/web-client/jobs/client-deploy.yml@templates
        parameters:
          deploymentName: 'deploy_web'
          dependsOn: ''
          serviceConnection: '${{ variables.serviceConnection }}'
          clientEnv: '${{ variables.envName }}'
          configURI: '${{ variables.configURI }}'
          rgName: '${{variables.rgName}}'
          kvSharedName: '${{ variables.kvSharedName }}'
          kvName: '${{ variables.kvName }}'
          envLabel: '${{ variables.envLabel }}'
          envName: '${{ variables.envName }}'
          envGroup: '${{ variables.envGroupName }}'
          repository: '${{ variables.repositoryName }}'
          containerRegistry: '${{ variables.containerRegistry }}'
          appName: '${{ variables.appName }}'
          appConfigName: '${{ variables.appConfigName }}'

  # Deploy to test environment
  - stage: test
    displayName: 'Deploy to test'
    dependsOn: 'build'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
      envName: 'test'
      envLabel: 'non-prod'
      configURI: '${{ variables.functionAppName }}'
      rgName: '${{ variables.envRgName }}'
      envGroupName: '$(globalPrefix)-$(fullAppName)-${{ variables.envName }}'
      serviceConnection: '${{ variables.nonProdServiceConnection }}'
      containerRegistry: '${{ variables.containerRegistryName }}'

    jobs:
      - template: /src/resources/web-client/jobs/client-deploy.yml@templates
        parameters:
          deploymentName: 'deploy_web'
          dependsOn: ''
          serviceConnection: '${{ variables.serviceConnection }}'
          clientEnv: '${{ variables.envName }}'
          configURI: '${{ variables.configURI }}'
          rgName: '${{variables.rgName}}'
          kvSharedName: '${{ variables.kvSharedName }}'
          kvName: '${{ variables.kvName }}'
          envLabel: '${{ variables.envLabel }}'
          envName: '${{ variables.envName }}'
          envGroup: '${{ variables.envGroupName }}'
          repository: '${{ variables.repositoryName }}'
          containerRegistry: '${{ variables.containerRegistry }}'
          appName: '${{ variables.appName }}'
          appConfigName: '${{ variables.appConfigName }}'

  # Deploy to prod environment
  - stage: prod
    displayName: 'Deploy to prod'
    dependsOn: 'test'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
      envName: 'prod'
      envLabel: 'prod'
      configURI: '${{ variables.functionAppName }}'
      rgName: '${{ variables.envRgName }}'
      envGroupName: '$(globalPrefix)-$(fullAppName)-${{ variables.envName }}'
      serviceConnection: '${{ variables.prodServiceConnection }}'
      containerRegistry: '${{ variables.containerRegistryName }}'

    jobs:
      - template: /src/resources/web-client/jobs/client-deploy.yml@templates
        parameters:
          deploymentName: 'deploy_web'
          dependsOn: ''
          serviceConnection: '${{ variables.serviceConnection }}'
          clientEnv: '${{ variables.envName }}'
          configURI: '${{ variables.configURI }}'
          rgName: '${{variables.rgName}}'
          envGroup: '${{ variables.envGroupName }}'
          repository: '${{ variables.repositoryName }}'
          containerRegistry: '${{ variables.containerRegistry }}'
          appName: '${{ variables.appName }}'
          appConfigName: '${{ variables.appConfigName }}'