import { FieldSettings } from '../../../../components/ParkView/Models/fieldSettings';
import { HandoverPackage } from '../models/handoverPackage';
import { getDateKey, getProgressKey } from './getKeyFunctions';
import { sortByNumber } from './sortFunctions';

export type ExtendedGardenFields = 'RFCC' | 'TAC' | 'RFOC' | 'DCC' | 'RFRC';

export const fieldSettings: FieldSettings<HandoverPackage, ExtendedGardenFields> = {
    RFCC: { label: 'RFCC', getKey: getDateKey, getColumnSort: sortByNumber },
    TAC: { label: 'TAC', getKey: getDateKey, getColumnSort: sortByNumber },
    RFOC: { label: 'RFOC', getKey: getDateKey, getColumnSort: sortByNumber },
    DCC: { label: 'DCC', getKey: getDateKey, getColumnSort: sortByNumber },
    RFRC: { label: 'RFRC', getKey: getDateKey, getColumnSort: sortByNumber },
    responsible: { label: 'Comm Pkg Responsible' },
    area: { label: 'Comm Pkg Area' },
    phase: { label: 'Comm Pkg Phase' },
    progress: { label: 'Comm Pkg Progress', getKey: getProgressKey, getColumnSort: sortByNumber },
    system: { label: 'System' },
    priority1: { label: 'Commissioning Priority 1' },
    priority2: { label: 'Commissioning Priority 2' },
    priority3: { label: 'Commissioning Priority 3' },
};
export const hiddenColumns: (keyof HandoverPackage)[] = [
    'siteCode',
    'projectIdentifier',
    'projectDescription',
    'progress',
    'area',
    'priority1Description',
    'priority2Description',
    'priority3Description',
    'actualStartDate',
    'plannedFinishDate',
    'actualFinishDate',
    'url',
    'id',
    'hasUnsignedActions',
    'forecastFinishDate',
    'volume',
    'forecastTacDate',
    'mcPkgsCount',
    'mcPkgsRFCCShippedCount',
    'mcPkgsRFCCSigned',
    'mcPkgsRFOCShipped',
    'mcPkgsRFOCSigned',
    'tacIsAccepted',
    'tacIsShipped',
    'tacIsRejected',
    'plannedTacDate',
    'mcDisciplineCodes',
    'mcDisciplines',
    'isSubsea',
    'isDemolition',
    'demolitionPlannedStartDate',
    'demolitionForecastStartDate',
    'demolitionActualStartDate',
    'demolitionPlannedFinishDate',
    'demolitionForecastFinishDate',
    'demolitionActualFinishDate',
    'createdDate',
    'remark',
    'rfocIsShipped',
    'rfocIsAccepted',
    'rfocIsRejected',
    'rfccIsShipped',
    'rfccIsAccepted',
    'rfccIsRejected',
    'subSystem',
    'isReadyForStartup',
    'isInOperation',
    'hasMaintenanceProgram',
    'hasYellowLineMarkup',
    'hasBlueLineMarkup',
    'yellowLineStatus',
    'blueLineStatus',
    'hasOperationAgreement',
    'demolitionDCCAcceptedDate',
    'demolitionRFRCShippedDate',
    'tacActualDate',
    'rfccShippedDate',
    'rfocShippedDate',
    'rowKey',
];
