name: CI

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: PNPM setup
        uses: ./.github/actions/pnpm-setup

      - name: Build
        run: pnpm build

      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@master
        with:
          args: --debug
