name: "Deploy PR to dev🚀"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which env to set the service message in"
        default: "dev"
        required: true
        type: choice
        options:
          - dev
          - dev2

permissions:
  contents: write

jobs:
  deploy:
    name: Build and deploy to ${{inputs.environment}}
    environment:
      name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Push to ${{inputs.environment}}
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          git config user.name radix-pipeline
          git config user.email github-actions@github.com
          git fetch
          git push --force origin $BRANCH_NAME:${{inputs.environment}}
